openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Core
  license:
    name: MIT
servers:
  - url: http://core.swagger.io/v1
paths:
  /employees:
    get:
      summary: List all employees
      operationId: listEmployees
      tags:
        - employees
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of employees
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Employees"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create an employee
      operationId: createEmployees
      tags:
        - employees
      responses:
        201:
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /employees/{employeeId}:
    get:
      summary: Info for a specific employee
      operationId: showEmployeeById
      tags:
        - employees
      parameters:
        - name: employeeId
          in: path
          required: true
          description: The id of the employee to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employees"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Employee:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Employees:
      type: array
      items:
        $ref: "#/components/schemas/Employee"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
